\documentclass{report}
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{User's guide}

<<style-knitr, echo=FALSE, results="asis">>=
BiocStyle::latex(relative.path=TRUE)
@

\bioctitle[\Biocpkg{csaw} User's Guide]{\Biocpkg{csaw}: ChIP-seq analysis with windows}
\begin{document}
            
The user's guide has been migrated to \url{\Sexpr{file.path("http://bioconductor.org/books", BiocManager::version(), "csawBook")}}.

\end{document}
